#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define AVERAGE_LOOP 25
#define MEASUREMENT_DELAY 500
#define VOLTAGE_CALIBRATION 0.002
#define BOARD_VOLTAGE 3.33
#define ADC_MAX 4095
#define NORMALISE_VOLTAGE 1.5

#endif /*_CONSTANTS_H_*/
